export const NO_ACTION_DEFINED = 'WorkingTimeRecords/PUT';
export const MU_TOOGLE_NAV_DRAWER = 'MU_TOOGLE_NAV_DRAWER';
export const MU_SET_AUTH_STATUS = 'MU_SET_AUTH_STATUS';
export const MU_LOADING_DATA = 'MU_LOADING_DATA';
export const MU_GET_ERROR = 'MU_GET_ERROR';
export const GET_USE_AUTHENTICATION = 'GET_USE_AUTHENTICATION';
export const ACTION_LOGIN = 'ACTION_LOGIN';
export const MU_REGISTER_STATUS = 'MU_REGISTER_STATUS';
export const ACTION_REGISTER = 'ACTION_REGISTER';
export const MU_SET_AUTH_ACCESS_TOKEN = 'MU_SET_AUTH_ACCESS_TOKEN';
export const ACTION_NOT_DEFINED = 'ACTION_NOT_DEFINED';
export const GET_REGISTER_STATUS = 'GET_REGISTER_STATUS';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_CREATE_ACCOUNT = 'GET_CREATE_ACCOUNT';
export const ACTION_CREATE_ACCOUNT = 'ACTION_CREATE_ACCOUNT';
export const MU_CREATE_ACCOUNT = 'MU_CREATE_ACCOUNT';
export const GET_SAVE_PRODUCT_STATE = 'GET_SAVE_PRODUCT_STATE';
export const ACTION_SAVE_PRODUCT_STATE = 'ACTION_SAVE_PRODUCT_STATE';
export const MU_SAVE_PRODUCT_STATE = 'MU_SAVE_PRODUCT_STATE';
export const GET_LOAD_PRODUCT_FILE = 'GET_LOAD_PRODUCT_FILE';
export const ACTION_LOAD_PRODUCT_FILE = 'ACTION_LOAD_PRODUCT_FILE';
export const MU_LOAD_PRODUCT_FILE = 'MU_LOAD_PRODUCT_FILE';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const ACTION_ALL_PRODUCTS = 'ACTION_ALL_PRODUCTS';
export const MU_ALL_PRODUCTS = 'MU_ALL_PRODUCTS';
export const GET_DONATION = 'GET_DONATION';
export const ACTION_DONATION = 'ACTION_DONATION';
export const MU_DONATION = 'MU_DONATION';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const ACTION_ALL_USERS = 'ACTION_ALL_USERS';
export const MU_ALL_USERS = 'MU_ALL_USERS';
export const GET_SEND_EMAIL_TO_HP = 'GET_SEND_EMAIL_TO_HP';
export const ACTION_SEND_EMAIL_TO_HP = 'GET_SEND_EMAIL_TO_HP';
export const MU_SEND_EMAIL_TO_HP = 'GET_SEND_EMAIL_TO_HP';




