export const NO_ACTION_DEFINED = 'WorkingTimeRecords/PUT';
export const MU_TOOGLE_NAV_DRAWER = 'MU_TOOGLE_NAV_DRAWER';
export const MU_SET_AUTH_STATUS = 'MU_SET_AUTH_STATUS';
export const MU_LOADING_DATA = 'MU_LOADING_DATA';
export const MU_GET_ERROR = 'MU_GET_ERROR';
export const GET_USE_AUTHENTICATION = 'GET_USE_AUTHENTICATION';
export const ACTION_LOGIN = 'ACTION_LOGIN';
export const MU_REGISTER_STATUS = 'MU_REGISTER_STATUS';
export const ACTION_REGISTER = 'ACTION_REGISTER';
export const MU_SET_AUTH_ACCESS_TOKEN = 'MU_SET_AUTH_ACCESS_TOKEN';
export const ACTION_NOT_DEFINED = 'ACTION_NOT_DEFINED';
export const GET_REGISTER_STATUS = 'GET_REGISTER_STATUS';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_CREATE_ACCOUNT = 'GET_CREATE_ACCOUNT';
export const ACTION_CREATE_ACCOUNT = 'ACTION_CREATE_ACCOUNT';
export const MU_CREATE_ACCOUNT = 'MU_CREATE_ACCOUNT';









