export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const ACTION_LOAD_USER_PROFILE = 'ACTION_LOAD_USER_PROFILE';
export const SET_ACTIVE_USER_PROFILE = 'SET_ACTIVE_USER_PROFILE';
export const GET_USER_PROFILE_LOADING_STATE = 'GET_USER_PROFILE_LOADING_STATE';

